### PR TITLE
update stackage

### PR DESCRIPTION
**Pull request by shmish111**

### CODE REVIEW

**Comment by shmish111** [comment]
I'm currently in the process of upgrading purescript so I need your branch, I would really like to get it merged into the original repo though.

**Comment by CarstenKoenig** [comment]
wouldn't it be easier for you to fork this for yourself an build on it?

I'll happily merge this for you here but I probably won't get the time to look into it before this weekend

**Comment by CarstenKoenig** [comment]
as for the original repo - if I remember correctly the main problem here is that the example is depending on `purescript-servant-subscribe` (or something like this) as well and this complicates matters a bit

IMO it's probably better to cut down on the example to the basics and rebuild from there

that's where I left this (sorry)

**Comment by CarstenKoenig** [comment]
I had some unfinished work left on disk - maybe you can start from there - I'll try to have a look again

**Pull request merged**
